### ISSUE TITLE
ID = None cause File id mismatch errors on first upload

### ISSUE THREAD

**Issue by GyroLand** [iwonbigbro/gsync#66]
Hi!

When uploading new files to drive, the ID comes up as None (as defined by SyncFileLocal.getInfo, i guess) in the properties, and this causes a http 400 error saying File ID mismatch.
I could actually fix this by changing the create method in class _Drive like this:
```
for k, v in properties.iteritems():
            if v is not None:
                body[k] = _Drive.utf8(v)
```
I am just not sure that this won't cause any other problems. I am using the latest pip version, not the git one. But i think the same would happen in the git version as well.

**Comment by benfry** [comment]
@sudsy I hadn't yet—I wasn't able to confirm whether the changes were enough to give me a working repo, but it looks like @iwonbigbro has merged them since. Thanks!

**Comment by guillaumemorin** [comment]
I've just installed the 0.1.14 version with pip on Debian 7.7 and I had to make the fix too (in /usr/local/lib/python2.7/dist-packages/libgsync/drive/**init**.py). Works well now, thx @GyroLand ;)

**Comment by ramicio** [comment]
This doesn't work for me. First off, the --authentication flag doesn't do anything for me. It's not even listed under my help. Secondly, it doesn't upload anything. 0 bytes. I apply this "fix," and I just get errors:

Traceback (most recent call last):
  File "/usr/local/bin/gsync", line 8, in <module>
    from libgsync.crawler import Crawler
  File "/usr/local/lib/python2.7/dist-packages/libgsync/crawler.py", line 4, in <module>
    from libgsync.sync import Sync
  File "/usr/local/lib/python2.7/dist-packages/libgsync/sync/**init**.py", line 5, in <module>
    from libgsync.drive.mimetypes import MimeTypes
  File "/usr/local/lib/python2.7/dist-packages/libgsync/drive/**init**.py", line 646
    body[k] = _Drive.utf8(v)
                           ^
IndentationError: unindent does not match any outer indentation level

**Comment by arielscarpinelli** [comment]
@iwonbigbro Could you please release a new version including this fix? You merged the patch in Jan but seems that never released the update to pypi. Thanks!

**Comment by tevch** [comment]
yes, please
i got the same issue, same fix
but please release it to pip
