### ISSUE TITLE
Only synching dirs. Not Files?

### ISSUE THREAD

**Issue by jonomcclelland** [iwonbigbro/gsync#90]
I tested pushing a small directory of files:
a/a1
a/b/b1
a/b/c/c1

Problem 1: Doesn't push top dir "a". Ignores it.
$ gsync -vcrlstI a drive://BACKUPS/
sent 0 bytes  received 0 bytes  0.00 bytes/sec

If I rename "a" to "testsync" it starts to work better:
$ mv a testsync
$ gsync -vcrlstI testsync drive://BACKUPS/
testsync/
testsync/a1
testsync/b/
testsync/b/b1
testsync/b/c/
testsync/b/c/c1
sent 0 bytes  received 0 bytes  0.00 bytes/sec

Problem 2: The above command just synched the dirs, ignoring the files:
![gsync](https://cloud.githubusercontent.com/assets/9307670/6079156/54727ca2-adf9-11e4-8502-7c0bdecdd26a.png)

Anyone seen issues like this? Am I using the wrong options?

**Comment by dmutters** [comment]
This is a duplicate of #69.  A workaround is included in that bug's thread.

**Comment by jonomcclelland** [comment]
Thanks for the feedback. Apologies for the duplicate.
